### ISSUE TITLE
Complete figures o

### ISSUE THREAD

**Issue by pcarval1** [meren/oligotyping#20]
I finally arrived to oligotyping command, and obtain the following (several results files, but no figures..and I need the entropy figures for each oligotype to choose the positions for the second run. So I am stopped at this point. Please help me :

Output directory .................................................: /home/oligotyping/TOTLplantlimp_aligned_pfilteredMEGA-c1-s1-a0.0-A0-M10
Temporary files directory ........................................: /home/oligotyping/TOTLplantlimp_aligned_pfilteredMEGA-c1-s1-a0.0-A0-M10/TMP
Extraction info output file ......................................: /home/oligotyping/TOTLplantlimp_aligned_pfilteredMEGA-c1-s1-a0.0-A0-M10/RUNINFO
Quality scores were provided .....................................: False
Command line .....................................................: /usr/bin/oligotype TOTLplantlimp_aligned_pfilteredMEGA.fasta TOTLplantlimp_aligned_pfilteredMEGA.fasta-ENTROPY -c1 -M10 --gen-html
Number of sequences analyzed .....................................: 6,818
Number of characters in each alignment ...........................: 496
Number of entropy components to be selected automatically ........: 1
Number of entropy components chosen by the user ..................: 0
Oligotype sets were requested to be generated ....................: False
Skip performing basic analyses ...................................: False
Min number of samples oligotype expected to appear ...............: 1
Min % abundance of oligotype in at least one sample ..............: 0.0
Min total abundance of oligotype in all samples ..................: 0
Min substantive abundance of an oligotype (-M) ...................: 10
Base locations of interest in the alignment ......................: 1
Number of samples found ..........................................: 7           
Number of unique oligotypes (raw) ................................: 4           
Oligotypes after "min number of samples" elimination .............: 4           
Oligotypes after "min % abundance in a sample" elimination .......: 4           
Oligotypes after "min total abundance (-A)" elimination ..........: 4           
Oligotypes after "min substantive abundance (-M)" elimination ....: 2           
Number of sequences represented after quality filtering ..........: 6,803       
Random colors for oligotypes .....................................: /home/oligotyping/TOTLplantlimp_aligned_pfilteredMEGA-c1-s1-a0.0-A0-M10/COLORS
FASTA file for abundant oligotypes ...............................: /home/oligotyping/TOTLplantlimp_aligned_pfilteredMEGA-c1-s1-a0.0-A0-M10/OLIGOS.fasta
NEXUS file for abundant oligotypes ...............................: /home/oligotyping/TOTLplantlimp_aligned_pfilteredMEGA-c1-s1-a0.0-A0-M10/OLIGOS.nexus
Environment file .................................................: /home/oligotyping/TOTLplantlimp_aligned_pfilteredMEGA-c1-s1-a0.0-A0-M10/ENVIRONMENT.txt
Sample/oligotype abundance data matrix (counts) ..................: /home/oligotyping/TOTLplantlimp_aligned_pfilteredMEGA-c1-s1-a0.0-A0-M10/MATRIX-COUNT.txt
Sample/oligotype abundance data matrix (percents) ................: /home/oligotyping/TOTLplantlimp_aligned_pfilteredMEGA-c1-s1-a0.0-A0-M10/MATRIX-PERCENT.txt
Read distribution among samples table ............................: /home/oligotyping/TOTLplantlimp_aligned_pfilteredMEGA-c1-s1-a0.0-A0-M10/READ-DISTRIBUTION.txt
[24 Jul 15 13:00:37 Generating Entropy Figures] 0 of 2 done in 0 threads ( (...)

**Comment by meren** [comment]
This morning I got this same message from 3 different sources: as an e-mail, as a comment to the oligotyping page, and as a bug report. Yet none of these are the preferred method of dealing with these issues. There is a Google Groups for these questions linked from the [oligotyping project page](http://merenlab.org/projects/oligotyping/):

https://groups.google.com/forum/#!forum/oligotyping

Please ask your question there.
