### ISSUE TITLE
Dead URL

### ISSUE THREAD

**Issue by pbuttigieg** [meren/oligotyping#23]
Here's the offender: http://oligotyping.org/2014/08/16/installing-the-oligotyping-pipeline/
linked to from http://oligotyping.org/MED/ in the following text: 
>The installation of the oligotyping pipeline is explained [here](http://oligotyping.org/2014/08/16/installing-the-oligotyping-pipeline/).

**Comment by meren** [comment]
Hi Pier!

Thank you very much for reporting this. I updated http://oligotyping.org/MED/ to redirect that page to our new location.


Best wishes,
