### ISSUE TITLE
Not all reads have the same length

### ISSUE THREAD

**Issue by nikolay12** [meren/oligotyping#25]
I'm struggling with the MED pipeline.

I have paired end data containing reads of identical length. What I have done so far:

**Step. 1. Create a TAB-delimited file containing all sample names and the corresponding files**

I based this on [these explanations](https://github.com/meren/illumina-utils#config-file-format).

**Step. 2. Using the above TAB-delimited file I generated config files**

I used _iu-gen-configs_ with the above TAB-delimited file. I was expecting that a single config file will be generated. Instead a separate config file for each sample was generated. I think my subsequent troubles are due to this unexpected behaviour.

**Step. 3. I ran `iu-merge-pairs --ignore-deflines`  for each sample**

**Step. 4. I merged all the _MERGED fasta files into a single file while taking care that the header is of the requested format**

**Step. 5. I checked with the _o-get-sample-info-from-fasta_ that the fasta headers were, indeed, correct**

**Step. 6. I ran _decompose_ with the above fasta file**

And here I got 

> Config Error: Not all reads have the same length.

To me it looks that the issue is due to the merge process producing composite reads of different length. I presume that the merging shall be done for the whole dataset as a whole, rather than for each sample individually.

How to best proceed from here?

**Comment by meren** [comment]
> To me it looks that the issue is due to the merge process producing composite reads of different length.

It is not an issue, it is biology. You can use `o-pad-with-gaps` script if it applies to you:

http://merenlab.org/2014/09/14/oligotyping-and-alignment/


Best,
